// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBQtG-OB1WosFAkLXYL1djNffnsWLDOhdI',
    appId: '1:204606211916:web:721281ce438f6dd2afb1e9',
    messagingSenderId: '204606211916',
    projectId: 'kamha-15aea',
    authDomain: 'kamha-15aea.firebaseapp.com',
    storageBucket: 'kamha-15aea.appspot.com',
    measurementId: 'G-6WEJNFB9X1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCiyUpb1UchkgO1OiC9DTwFdLp2l6BF2Ro',
    appId: '1:204606211916:android:25032ab9ec018752afb1e9',
    messagingSenderId: '204606211916',
    projectId: 'kamha-15aea',
    storageBucket: 'kamha-15aea.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDqiJqg9EC4RFn2AmoKEvhjIBKigMElN-U',
    appId: '1:204606211916:ios:efdde509d190bb9dafb1e9',
    messagingSenderId: '204606211916',
    projectId: 'kamha-15aea',
    storageBucket: 'kamha-15aea.appspot.com',
    iosBundleId: 'com.example.agro',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDqiJqg9EC4RFn2AmoKEvhjIBKigMElN-U',
    appId: '1:204606211916:ios:c51f87049327f06bafb1e9',
    messagingSenderId: '204606211916',
    projectId: 'kamha-15aea',
    storageBucket: 'kamha-15aea.appspot.com',
    iosBundleId: 'com.example.agro.RunnerTests',
  );
}
